/*PRUEBA RN1_SANCION*/

INSERT INTO usuarios VALUES ('20076584d', 'Manuel', 'Rodriguez, Perez', null
    , 'manuelrp@hotmail.com', 'desahucio', 'depresion',
    'estable', 5, null);

UPDATE usuarios SET NOMBRE='Manuel', APELLIDOS='Rodriguez, Perez', OBSERVACIONES=null,
    CONTACTO='manuelrp@hotmail.com', MOTIVO_INGRESO='desahucio', ESTADO_PSICOLOGICO='estable',
    ESTADO_MEDICO='Estable', SANCIONES=6, PREMIOS=null WHERE DNI = '20076584d';
    
/*PRUEBA RN3_ELIMINACION_DATOS*/


DELETE FROM usuarios WHERE DNI = '20076584d';

/*PRUEBA RN4_CREACION_ACTIVIDAD*/

INSERT INTO actividades VALUES (0,'Sevilla', '29/09/2016', 10, 'Positivas');

UPDATE actividades SET OID_ACT=1, LUGAR='Parque Oromana', FECHA='06-09-2016', NUMERO_ASISTENTES=4,
    CALIFICACIONES='positivas' WHERE OID_ACT = 0;


/*PRUEBA RN5_INSCRIPCIOIN_ACTIVIDAD*/




/*PRUEBA RN8_DISPONIBILIDAD_PRESTAMOS*/
INSERT INTO MATERIALES_PRESTADOS VALUES( SEC_OID_MPR.nextval, 'nombre', 'f', 'f', 8, 'libro');
INSERT INTO PRESTAMOS VALUES(SEC_OID_MPR.nextval, '29987456T', '28-09-2017', '29-09-2017', 'F', 'MANOLI' );

 UPDATE prestamos SET DNI='20076584d', FECHA_INICIO='26-07-2016', FECHA_FIN='29-07-2016',
 DEVOLUCION='F', NOMBRE_ENCARGADO='Manuel' WHERE OID_PRE = 1;

/*PRUEBA RN7_CONTROL_PRESTAMOS*/
INSERT INTO PRESTAMOS VALUES ('20090673r','29-09-2018', '30-09-208', 'f', 'pepa');

UPDATE PRESTAMOS SET DNI= '20090673r',FECHA_INICIO='29-09-2018',FECHA_FIN= '30-09-2018',
DEVOLUCION= 'f',NOMBRE_ENCARGADO= 'pepa' WHERE OID_PRE=4;


--Tarea: PRUEBA T_ALOJAMIENTOS*/--
/*PRUEBA T_MATERIALES*/
INSERT INTO MATERIALES_PRESTADOS VALUES (2,'David', 'T', 'Bueno', 2, 'libro');
UPDATE  MATERIALES_PRESTADOS SET NOMBRE= 'David',DISPONIBILIDAD= 'T',ESTADO_DEVOLUCION= 'Bueno',
    CANTIDAD=1 , TIPO= 'libro';

/*PRUEBA T_DEVOLUCION*/
INSERT INTO PRESTAMOS VALUES(1, '29987456T', '28-09-2017', '29-09-2017', 'F', 'MANOLI' );

 UPDATE prestamos SET DNI='20076584d', FECHA_INICIO='26-07-2016', FECHA_FIN='29-07-2016',
 DEVOLUCION='F', NOMBRE_ENCARGADO='Manuel' WHERE OID_PRE = 1;

/*PRUEBA T_INSCRIPCIONES*/

INSERT INTO INSCRIPCIONES VALUES(SEC_OID_INS.nextval, '636362728F', 7, '5-09-2016', 'DFHVUHISDV@gmail.com');

UPDATE INSCRIPCIONES SET OID_INS= SEC_OID_EST.nextval, DNI='47465858D', OID_ACT= 7, FECHA='5-09-2016',
                            CORREO_ELECTRONICO= 'fvid@gmail.com' WHERE OID_INS= 1;